### ISSUE TITLE
`Promise` doesn't provide variants of `catch` and `either` where the rejection function returns another `Promise`

### ISSUE THREAD

**Issue by fsoikin** [fable-compiler/fable-powerpack#23]
According to the [spec](http://www.ecma-international.org/ecma-262/6.0/#sec-promise.prototype.catch), `Promise.catch(f)` is sugar for `Promise.then(id, f)`, which allows `f : exn -> U2<'T, Promise<'T>>`, whereas the Fable.PowerPack's current implementations only allow `f : exn -> 'T`.

To avoid breaking changes, I propose not to change the signatures of `catch` and `either`, but add two new functions, `catchBind` and `eitherBind` respectively:

```
[<Emit("$1.catch($0)")>]
let catchBind (a: Exception->Promise<'T>) (pr: JS.Promise<'T>): JS.Promise<'T> = jsNative

[<Emit("$2.then($0,$1)")>]
let eitherBind (success: 'T->'R) (fail: Exception->Promise<'R>) (pr: JS.Promise<'T>): JS.Promise<'R> = jsNative
```

(I'm not completely sure about the names - not a native English speaker myself - so if anyone has better ideas...)

**Comment by alfonsogarciacaro** [comment]
I think that's a good idea! Though maybe the signature of eitherBind should be the following? (So `success` also returns a Promise.)

```fsharp
let eitherBind (success: 'T->Promise<'R>) (fail: Exception->Promise<'R>) (pr: JS.Promise<'T>): JS.Promise<'R> = jsNative
```

I know this reduces flexibility, maybe we could do something like this, although it may not be very pretty:

```fsharp
let eitherBind (success: 'T->U2<'R,Promise<'R>>) (fail: Exception->Promise<'R>) (pr: JS.Promise<'T>): JS.Promise<'R> = jsNative
```

We could use the `!^` operator for combination (for example, return a non-promise in success and a promise in fail):

```fsharp
myPromise
|> Promise.eitherBind (fun x -> !^(string x)) (fun ex -> !^(Promise.lift ex.Message))
```

**Comment by MangelMaxime** [comment]
Hum, I am asking myself if it's a good idea to add "custom" methods in the libs instead of fixing it. If I understand correctly, we are less permissive than the official API.

The compiler should, generate an error when the user update it's deps and so help him identified and fix the errors.

**Comment by alfonsogarciacaro** [comment]
@MangelMaxime In principle you're right, but we must be careful with this, because it's always annoying to find that your code is not compiling anymore after updating a dependency and sometimes it's difficult to figure out how to fix the error right away.

In any case, we need to decide if we do need to fix this and how. It's true the JS API (`.then`) is more flexible than the F# one, but I think it's OK to have two methods (`map` and `bind`) because they're standard in most functional languages. For catch, I'd say it's also OK to have both `catch` and `catchBind` for the same reasons.

The trickiest part is `either` as it allows four combinations (non-promise/non-promise, promise/promise, non-promise/promise, promise/non-promise). If we decided to go for the `('T->U2<'R,Promise<'R>>) -> (Exception->U2<'R,Promise<'R>>) -> JS.Promise<'T> -> JS.Promise<'T>` signature, it may make sense to directly modify `either`, yes (though it's a breaking change).

**Comment by MangelMaxime** [comment]
Ok, I understand :)

Seems fine to me. Just either type signature which looks complex :)

**Comment by fsoikin** [comment]
I was not aware of the existence of the "erased cast" operator, and my chief concern was with the awkwardness of inserting `U2.Case1` everywhere, but now I that I know that the operator exists, I think that we should fix the signature of `either` instead of adding `eitherBind`. The justification is that `either` probably represents am "advanced" usage, and therefore it is both more rare in existing code and practiced by more experienced developers, who wouldn't be confused by the changed signature as much.

By the reverse reasoning, and agreeing with @alfonsogarciacaro, I agree with adding `catchBind`.

**Comment by alfonsogarciacaro** [comment]
It seems we reached an agreement ;) @fsoikin Would you mind sending a PR to modify the signature of `Promise.either`? Ideally adding an explanation in the help comment on how to use the `!^` operator. Cheers!
